"""Multi-Agent System module for Company Intelligence GraphRAG.

Provides typed shared state management, agent role contracts, evidence provenance,
execution budget limits, Planner, Supervisor, Vector Researcher, Graph Researcher,
Evidence Verifier, Report Writer agents, JSON Checkpoint Persistence, Durable Workflow,
Observability Tracing, and Security Guardrails.
"""

from company_graphrag.agents.contracts import (
    AGENT_CONTRACTS,
    AgentContract,
    AgentRole,
    GraphResearcherInput,
    GraphResearcherOutput,
    PlannerInput,
    PlannerOutput,
    ReportWriterInput,
    ReportWriterOutput,
    SupervisorInput,
    SupervisorOutput,
    VectorResearcherInput,
    VectorResearcherOutput,
    VerifierInput,
    VerifierOutput,
)
from company_graphrag.agents.observability import (
    AgentGuardrails,
    AgentTracer,
    RunMetrics,
    SecurityViolationError,
    TraceRecord,
)
from company_graphrag.agents.planner import KNOWN_COMPANIES, PlannerAgent
from company_graphrag.agents.researchers import (
    EvidenceDeduplicator,
    GraphResearcherAgent,
    ResearcherExecutionResult,
    VectorResearcherAgent,
)
from company_graphrag.agents.schema import (
    AgentWorkflowStatus,
    CitationItem,
    Contradiction,
    EvidenceItem,
    ExecutionBudget,
    RejectedClaim,
    ReportOutput,
    ResearchPlan,
    ResearchState,
    ResearchTaskStep,
    SubQuestion,
    ToolCallRecord,
    VerifiedClaim,
)
from company_graphrag.agents.supervisor import SupervisorAgent
from company_graphrag.agents.verifier import EvidenceVerifierAgent
from company_graphrag.agents.workflow import (
    CheckpointCorruptError,
    CheckpointNotFoundError,
    JSONCheckpointSaver,
    ResearchWorkflow,
    WorkflowInterruptReason,
    WorkflowStage,
)
from company_graphrag.agents.writer import CitationCompletenessChecker, ReportWriterAgent

__all__ = [
    "AGENT_CONTRACTS",
    "KNOWN_COMPANIES",
    "AgentContract",
    "AgentGuardrails",
    "AgentRole",
    "AgentTracer",
    "AgentWorkflowStatus",
    "CheckpointCorruptError",
    "CheckpointNotFoundError",
    "CitationCompletenessChecker",
    "CitationItem",
    "Contradiction",
    "EvidenceDeduplicator",
    "EvidenceItem",
    "EvidenceVerifierAgent",
    "ExecutionBudget",
    "GraphResearcherAgent",
    "GraphResearcherInput",
    "GraphResearcherOutput",
    "JSONCheckpointSaver",
    "PlannerAgent",
    "PlannerInput",
    "PlannerOutput",
    "RejectedClaim",
    "ReportOutput",
    "ReportWriterAgent",
    "ReportWriterInput",
    "ReportWriterOutput",
    "ResearcherExecutionResult",
    "ResearchPlan",
    "ResearchState",
    "ResearchTaskStep",
    "ResearchWorkflow",
    "RunMetrics",
    "SecurityViolationError",
    "SubQuestion",
    "SupervisorAgent",
    "SupervisorInput",
    "SupervisorOutput",
    "ToolCallRecord",
    "TraceRecord",
    "VectorResearcherAgent",
    "VectorResearcherInput",
    "VectorResearcherOutput",
    "VerifiedClaim",
    "VerifierInput",
    "VerifierOutput",
    "WorkflowInterruptReason",
    "WorkflowStage",
]
