companies:
  - id: akbank

    name: Akbank T.A.Ş.
    aliases:
      - Akbank
      - Akbank T.A.Ş.
      - Akbank T.A.S.
    official_domains:
      - akbank.com
      - akbankinvestorrelations.com
      - akbankinvestorrelations.com/tr/finansal-bilgiler/faaliyet-raporlari.aspx
    years: [2023, 2024, 2025]


  - id: arcelik
    name: Arçelik A.Ş.
    aliases:
      - Arçelik
      - Arçelik A.Ş.
      - Arcelik A.S.
      - Beko
    official_domains:
      - arcelikglobal.com
      - arcelik.com.tr
    years: [2023, 2024, 2025]

  - id: aselsan
    name: Aselsan Elektronik Sanayi ve Ticaret A.Ş.
    aliases:
      - Aselsan
      - Aselsan A.Ş.
      - Aselsan Elektronik Sanayi ve Ticaret A.Ş.
    official_domains:
      - aselsan.com.tr
      - aselsan.com
    years: [2023, 2024, 2025]

  - id: ford_otosan
    name: Ford Otomotiv Sanayi A.Ş.
    aliases:
      - Ford Otosan
      - Ford Otomotiv
      - Ford Otomotiv Sanayi A.Ş.
    official_domains:
      - fordotosan.com.tr
    years: [2023, 2024, 2025]

  - id: koc_holding
    name: Koç Holding A.Ş.
    aliases:
      - Koç Holding
      - Koc Holding
      - Koç Holding A.Ş.
    official_domains:
      - koc.com.tr
    years: [2023, 2024, 2025]

  - id: migros
    name: Migros Ticaret A.Ş.
    aliases:
      - Migros
      - Migros Ticaret
      - Migros Ticaret A.Ş.
    official_domains:
      - migroskurumsal.com
      - migros.com.tr
      - migroskurumsalstr.blob.core.windows.net
    years: [2023, 2024, 2025]

  - id: sisecam
    name: Türkiye Şişe ve Cam Fabrikaları A.Ş.
    aliases:
      - Şişecam
      - Sisecam
      - Türkiye Şişe ve Cam Fabrikaları A.Ş.
    official_domains:
      - sisecam.com.tr
      - sisecam.com
    years: [2023, 2024, 2025]

  - id: turkcell
    name: Turkcell İletişim Hizmetleri A.Ş.
    aliases:
      - Turkcell
      - Turkcell İletişim Hizmetleri A.Ş.
    official_domains:
      - turkcell.com.tr
      - turkcell.com
    years: [2023, 2024, 2025]

  - id: thyao
    name: Türk Hava Yolları A.O.
    aliases:
      - Türk Hava Yolları
      - Turkish Airlines
      - Türk Hava Yolları A.O.
    official_domains:
      - turkishairlines.com
      - investor.turkishairlines.com
      - investor.turkishairlines.com/tr/finansal-ve-operasyonel-veriler/faaliyet-raporlari
    years: [2023, 2024, 2025]


  - id: tupras
    name: Türkiye Petrol Rafinerileri A.Ş.
    aliases:
      - Tüpraş
      - Tupras
      - Türkiye Petrol Rafinerileri A.Ş.
    official_domains:
      - tupras.com.tr
      - tupras.com
    years: [2023, 2024, 2025]
